# Generated by Django 5.1.6 on 2025-03-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="address_line", new_name="address",
        ),
    ]
